# Generated by Django 4.0.1 on 2022-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motdepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motdepasse_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pseudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_text', models.CharField(max_length=50)),
            ],
        ),
    ]
