# Generated by Django 4.0.1 on 2022-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_text', models.CharField(max_length=50)),
                ('motdepasse_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='motdepasse',
        ),
        migrations.DeleteModel(
            name='pseudo',
        ),
    ]
